domain: iometa.cn
language: en
# CDN, options: cdn.staticfile.org, cdnjs.cloudflare.com, cdnjs.cloudflare.com, 
cdn: cdn.staticfile.org

menu:
  Home: /
  About: /about
  Contact: /contact
  Archives: /archives


stylesheets:
- /css/lightx.css

scripts:
- /js/lightx.js
